version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/App.Dockerfile
    user: ${GITHUB_DOCKER_USER:-www-data}
    ports:
      - '8000:80'
    volumes:
      - .:/var/www/html
      - .docker/php.ini:/usr/local/etc/php/php.ini
      - .docker/apache-vhost.conf:/etc/apache2/sites-available/custom-vhost.conf
    container_name: poc_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: mysql
      DB_DATABASE: poc
      DB_USERNAME: poc
      DB_PASSWORD: poc
      DB_PORT: 3306
      DB_TEST_HOST: mysql
      DB_TEST_DATABASE: cake_test
      DB_TEST_USERNAME: cake_test
      DB_TEST_PASSWORD: cake_test
      DB_TEST_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
      - .docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: poc
      MYSQL_DATABASE: poc
      MYSQL_USER: poc
      MYSQL_PASSWORD: poc
    container_name: poc_mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8010:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: poc
    container_name: poc_phpmyadmin

  nodev1:
    image: node:14
    working_dir: /home/node/app/webroot/v1
    user: ${GITHUB_DOCKER_USER:-node}
    volumes:
      - ./:/home/node/app
    command: npm run watch
    container_name: poc_node_v1

  nodev2:
    build:
      context: .
      dockerfile: .docker/Node.Dockerfile
    user: ${GITHUB_DOCKER_USER:-node}
    working_dir: /home/node/app/webroot/v2
    volumes:
      - ./:/home/node/app
    command: quasar dev
    ports:
      - "8080:8080"
    container_name: poc_node_v2

volumes:
  db:
